name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '16.4.0'
    - run: npm install --force
    - run: npm run test:ci
    - run: npm run build:ci
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LABOS_B4616 }}'
          projectId: labos-b4616